version: '3'
services:
  phantomjs:
    image: wernight/phantomjs
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp2
    ports:
      - "3000:3000"
    depends_on:
      - db
